In [ ]:
import numpy as np
import pandas as pd
import matplotlib as pltf

In [ ]:
data = pd.read_csv("heart.csv")
data.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
y = data["output"]
x = data.drop("output", axis=1)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logistic = LogisticRegression().fit(x, y)
logistic.score(x, y)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8547854785478548

In [ ]:
data.shape

(303, 14)

In [ ]:
x_train, y_train = x[:200], y[:200]
x_train.shape, y_train.shape

((200, 13), (200,))

In [ ]:
x_test, y_test = x[200:], y[200:]
x_test.shape, y_test.shape

((103, 13), (103,))

In [ ]:
logistic_test = LogisticRegression().fit(x_train, y_train)
logistic_test.score(x_train, y_train), logistic_test.score(x_test, y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

(0.9, 0.5339805825242718)

In [ ]:
N = int(x.shape[0] * 0.8)

x_train, y_train, x_test, y_test = x[:N], y[:N], x[N:], y[N:]
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((242, 13), (242,), (61, 13), (61,))

In [ ]:
logistic_test = LogisticRegression().fit(x_train, y_train)
logistic_test.score(x_train, y_train), logistic_test.score(x_test, y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

(0.8884297520661157, 0.6229508196721312)

In [ ]:
N = int(x.shape[0] * 0.8)

x_train, y_train, x_test, y_test = x[:N], y[:N], x[N:], y[N:]
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((242, 13), (242,), (61, 13), (61,))

In [ ]:
logistic_test = LogisticRegression().fit(x_train, y_train)
logistic_test.score(x_train, y_train), logistic_test.score(x_test, y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

(0.8884297520661157, 0.6229508196721312)

In [ ]:
data.tail()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
mask = np.array([True] * N + [False] * (y.shape[0] - N))
mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
from numpy.random import shuffle

shuffle(mask)
mask

array([ True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
       False,  True, False,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True, False,
        True, False, False,  True, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False,  True, False,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
       False, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False,  True,  True,
       False,  True, False,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True, False,
        True,  True, False,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [ ]:
x_train = x[mask]
x_train.shape

(242, 13)

In [ ]:
x_train, y_train, x_test, y_test = x[mask], y[mask], x[~mask], y[~mask]
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((242, 13), (242,), (61, 13), (61,))

In [ ]:
logistic_test = LogisticRegression().fit(x_train, y_train)
logistic_test.score(x_train, y_train), logistic_test.score(x_test, y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

(0.8553719008264463, 0.8688524590163934)

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((242, 13), (242,), (61, 13), (61,))

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [ ]:
y_test_pred = logistic_test.predict(x_test)
y_train_pred = logistic_test.predict(x_train)

матрица классификации

In [ ]:
confusion_matrix(y_train, y_train_pred)

array([[ 85,  25],
       [  8, 124]])

In [ ]:
confusion_matrix(y_test, y_test_pred)

array([[22,  6],
       [ 4, 29]])

In [ ]:
precision_score(y_test, y_test_pred)

0.8285714285714286

In [ ]:
precision_score(y_train, y_train_pred)

0.8322147651006712

In [ ]:
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.85      0.79      0.81        28
           1       0.83      0.88      0.85        33

    accuracy                           0.84        61
   macro avg       0.84      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61

In [ ]:
print(classification_report(y_train, y_train_pred))

              precision    recall  f1-score   support

           0       0.91      0.77      0.84       110
           1       0.83      0.94      0.88       132

    accuracy                           0.86       242
   macro avg       0.87      0.86      0.86       242
weighted avg       0.87      0.86      0.86       242

In [ ]:
metrics = pd.DataFrame({
    "Train": [
        accuracy_score(y_train, y_train_pred),
        precision_score(y_train, y_train_pred),
        recall_score(y_train, y_train_pred),
        f1_score(y_train, y_train_pred),
    ],
    "Test": [
        accuracy_score(y_test, y_test_pred),
        precision_score(y_test, y_test_pred),
        recall_score(y_test, y_test_pred),
        f1_score(y_test, y_test_pred),
    ],
}, index = ["Accuracy", "Precision", "Recall", "F1"])

metrics

              Train      Test
Accuracy   0.863636  0.836066
Precision  0.832215  0.828571
Recall     0.939394  0.878788
F1         0.882562  0.852941

# ДЗ

## 1. Повторите анализ для других видов моделей. Используйте 5-10 разных классов моделей. Подсчитывайте только метрики на тестовой выборке.

In [ ]:
data = pd.read_csv("heart.csv")
data.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
y = data["output"]
x = data.drop("output", axis=1)

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, random_state = 1)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((242, 13), (242,), (61, 13), (61,))

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
models = {"Логистическая регрессия": LogisticRegression(),
    "Дерево решений": DecisionTreeClassifier(),
    "Случайный лес": RandomForestClassifier(),
    "Метод опорных векторов (без ядра)": SVC(),
    "Метод опорных векторов (с линейным ядром)": SVC(kernel='linear'),
    "Метод опорных векторов (с гауссовым ядром)": SVC(kernel='rbf'),
    "Метод опорных векторов (с полиномиальным ядром)": SVC(kernel='poly'),
    "Метод К ближайших соседей": KNeighborsClassifier(),
    "Наивный байесовский метод": GaussianNB(),
    "Многослойный перцептрон": MLPClassifier()
}
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print("\n")
    print(f"Model: {name}")
    print(f"Accuracy: {accuracy}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Model: Логистическая регрессия
Accuracy: 0.7540983606557377
Precision: 0.7222222222222222
Recall: 0.8387096774193549
F1 Score: 0.7761194029850746


Model: Дерево решений
Accuracy: 0.7049180327868853
Precision: 0.7096774193548387
Recall: 0.7096774193548387
F1 Score: 0.7096774193548387


Model: Случайный лес
Accuracy: 0.7704918032786885
Precision: 0.7297297297297297
Recall: 0.8709677419354839
F1 Score: 0.7941176470588235


Model: Метод опорных векторов (без ядра)
Accuracy: 0.5573770491803278
Precision: 0.5434782608695652
Recall: 0.8064516129032258
F1 Score: 0.6493506493506493


Model: Метод опорных векторов (с линейным ядром)
Accuracy: 0.7377049180327869
Precision: 0.7142857142857143
Recall: 0.8064516129032258
F1 Score: 0.7575757575757576


Model: Метод опорных векторов (с гауссовым ядром)
Accuracy: 0.5573770491803278
Precision: 0.5434782608695652
Recall: 0.8064516129032258
F1 Score: 0.6493506493506493


Model: Метод опорных векторов (с полиномиальным ядром)
Accuracy: 0.5901639344262295
Precision: 0.5714285714285714
Recall: 0.7741935483870968
F1 Score: 0.6575342465753424


Model: Метод К ближайших соседей
Accuracy: 0.5737704918032787
Precision: 0.5675675675675675
Recall: 0.6774193548387096
F1 Score: 0.6176470588235294


Model: Наивный байесовский метод
Accuracy: 0.7704918032786885
Precision: 0.7575757575757576
Recall: 0.8064516129032258
F1 Score: 0.78125


Model: Многослойный перцептрон
Accuracy: 0.7704918032786885
Precision: 0.717948717948718
Recall: 0.9032258064516129
F1 Score: 0.8

## 2. Повторите анализ для другого датасета по вашему выбору. Используйте несколько моделей для сравнения. Используйте датасет для множественной классификации.

In [ ]:
from sklearn.datasets import load_digits
data = load_digits()
X, y = data.data, data.target
print(data.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 1797
:Number of Attributes: 64
:Attribute Information: 8x8 image of integer pixels in the range 0..16.
:Missing Attribute Values: None
:Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
:Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each block. This generates
an input matrix of 8x8 where each element is an integer in the range
0..16. This reduces dimensionality and gives invariance to small
distortions.

For info on NIST preprocessing routines, see M. D. Garris, J. L. Blue, G.
T. Candela, D. L. Dimmick, J. Geist, P. J. Grother, S. A. Janet, and C.
L. Wilson, NIST Form-Based Handprint Recognition System, NISTIR 5469,
1994.

.. dropdown:: References

  - C. Kaynak (1995) Methods of Combining Multiple Classifiers and Their
    Applications to Handwritten Digit Recognition, MSc Thesis, Institute of
    Graduate Studies in Science and Engineering, Bogazici University.
  - E. Alpaydin, C. Kaynak (1998) Cascading Classifiers, Kybernetika.
  - Ken Tang and Ponnuthurai N. Suganthan and Xi Yao and A. Kai Qin.
    Linear dimensionalityreduction using relevance weighted LDA. School of
    Electrical and Electronic Engineering Nanyang Technological University.
    2005.
  - Claudio Gentile. A New Approximate Maximal Margin Classification
    Algorithm. NIPS. 2000.

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state = 1)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((1437, 64), (1437,), (360, 64), (360,))

In [ ]:
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    print("\n")
    print(f"Model: {name}")
    print(f"Accuracy: {accuracy}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Model: Логистическая регрессия
Accuracy: 0.9694444444444444
Precision: 0.9704552928785816
Recall: 0.9694444444444444
F1 Score: 0.9694329162605655


Model: Дерево решений
Accuracy: 0.8666666666666667
Precision: 0.870272411670298
Recall: 0.8666666666666667
F1 Score: 0.8665056383156938


Model: Случайный лес
Accuracy: 0.9861111111111112
Precision: 0.9866372247823861
Recall: 0.9861111111111112
F1 Score: 0.986155961413013


Model: Метод опорных векторов (без ядра)
Accuracy: 0.9916666666666667
Precision: 0.9919150025601638
Recall: 0.9916666666666667
F1 Score: 0.9917064294634811


Model: Метод опорных векторов (с линейным ядром)
Accuracy: 0.9916666666666667
Precision: 0.9920138888888889
Recall: 0.9916666666666667
F1 Score: 0.9917128800545086


Model: Метод опорных векторов (с гауссовым ядром)
Accuracy: 0.9916666666666667
Precision: 0.9919150025601638
Recall: 0.9916666666666667
F1 Score: 0.9917064294634811


Model: Метод опорных векторов (с полиномиальным ядром)
Accuracy: 0.9888888888888889
Precision: 0.9892084498536112
Recall: 0.9888888888888889
F1 Score: 0.9889303493344598


Model: Метод К ближайших соседей
Accuracy: 0.9944444444444445
Precision: 0.9945238095238095
Recall: 0.9944444444444445
F1 Score: 0.9944450114535847


Model: Наивный байесовский метод
Accuracy: 0.8527777777777777
Precision: 0.8867287475792832
Recall: 0.8527777777777777
F1 Score: 0.8543408491445494


Model: Многослойный перцептрон
Accuracy: 0.9777777777777777
Precision: 0.978302817228256
Recall: 0.9777777777777777
F1 Score: 0.9778554575709923

## 3. Повторите анализ для датасета, предназначенного для решения задачи регрессии. Используйте все метрики качества регрессии, изученные на лекции. Постройте 5 - 10 разных моделей регрессии.

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_squared_log_error, mean_absolute_percentage_error, median_absolute_error, max_error

data = fetch_california_housing()
X, y = data.data, data.target

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state = 1)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((16512, 8), (16512,), (4128, 8), (4128,))

In [ ]:
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

models = {"Линейная регрессия": LinearRegression(),
    "Дерево решений": DecisionTreeRegressor(),
    "Случайный лес": RandomForestRegressor(),
    "Метод опорных векторов (без ядра)": SVR(),
    "Метод опорных векторов (с гауссовым ядром)": SVR(kernel='rbf'),
    "Метод опорных векторов (с полиномиальным ядром)": SVR(kernel='poly'),
    "Метод К ближайших соседей": KNeighborsRegressor(),
    "Многослойный перцептрон": MLPRegressor()}

In [ ]:
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)
    medae = median_absolute_error(y_test, y_pred)
    max_er = max_error(y_test, y_pred)

    print("\n")
    print(f"Model: {name}")
    print(f"Средний квадрат ошибки (MSE): {mse}")
    print(f"Среднеквадратичная ошибка (RMSE): {rmse}")
    print(f"Средняя абсолютная ошибка (MAE): {mae}")
    print(f"Коэффициент детерминации (r-квадрат): {r2}")
    print(f"Среднее процентное отклонение (MAPE): {mape}")
    print(f"Абсолютная медианная ошибка: {medae}")
    print(f"Максимальная ошибка: {max_er}")

Model: Линейная регрессия
Средний квадрат ошибки (MSE): 0.5291402345397406
Среднеквадратичная ошибка (RMSE): 0.7274202599183918
Средняя абсолютная ошибка (MAE): 0.5328685121248204
Коэффициент детерминации (r-квадрат): 0.5965968374812278
Среднее процентное отклонение (MAPE): 0.32776956857031203
Абсолютная медианная ошибка: 0.4149817430260818
Максимальная ошибка: 5.869210734062835


Model: Дерево решений
Средний квадрат ошибки (MSE): 0.4922762182933624
Среднеквадратичная ошибка (RMSE): 0.7016239864010939
Средняя абсолютная ошибка (MAE): 0.4491585513565892
Коэффициент детерминации (r-квадрат): 0.6247010332429952
Среднее процентное отклонение (MAPE): 0.24485652292343507
Абсолютная медианная ошибка: 0.2569999999999999
Максимальная ошибка: 4.675009999999999


Model: Случайный лес
Средний квадрат ошибки (MSE): 0.2518610322108325
Среднеквадратичная ошибка (RMSE): 0.5018575816014266
Средняя абсолютная ошибка (MAE): 0.32418559617248077
Коэффициент детерминации (r-квадрат): 0.807987504489301
Среднее процентное отклонение (MAPE): 0.1852931145692792
Абсолютная медианная ошибка: 0.20070999999999978
Максимальная ошибка: 3.3737499999999985


Model: Метод опорных векторов (без ядра)
Средний квадрат ошибки (MSE): 1.320732383526986
Среднеквадратичная ошибка (RMSE): 1.149231214128378
Средняя абсолютная ошибка (MAE): 0.8591093473587433
Коэффициент детерминации (r-квадрат): -0.0068930419157673395
Среднее процентное отклонение (MAPE): 0.5351876205048365
Абсолютная медианная ошибка: 0.6790435606026106
Максимальная ошибка: 3.4884101771284786


Model: Метод опорных векторов (с гауссовым ядром)
Средний квадрат ошибки (MSE): 1.320732383526986
Среднеквадратичная ошибка (RMSE): 1.149231214128378
Средняя абсолютная ошибка (MAE): 0.8591093473587433
Коэффициент детерминации (r-квадрат): -0.0068930419157673395
Среднее процентное отклонение (MAPE): 0.5351876205048365
Абсолютная медианная ошибка: 0.6790435606026106
Максимальная ошибка: 3.4884101771284786


Model: Метод опорных векторов (с полиномиальным ядром)
Средний квадрат ошибки (MSE): 1.3383108163411583
Среднеквадратичная ошибка (RMSE): 1.15685384398426
Средняя абсолютная ошибка (MAE): 0.8636110889162558
Коэффициент детерминации (r-квадрат): -0.02029439552012713
Среднее процентное отклонение (MAPE): 0.5376751276401845
Абсолютная медианная ошибка: 0.6767409686406238
Максимальная ошибка: 3.7766099755063713


Model: Метод К ближайших соседей
Средний квадрат ошибки (MSE): 1.1291400878153661
Среднеквадратичная ошибка (RMSE): 1.0626100356270716
Средняя абсолютная ошибка (MAE): 0.8226058798449613
Коэффициент детерминации (r-квадрат): 0.13917208970577166
Среднее процентное отклонение (MAPE): 0.5538071669328409
Абсолютная медианная ошибка: 0.6585019999999999
Максимальная ошибка: 4.207409999999999


Model: Многослойный перцептрон
Средний квадрат ошибки (MSE): 1.44983935304386
Среднеквадратичная ошибка (RMSE): 1.2040927510137498
Средняя абсолютная ошибка (MAE): 1.0308750245564937
Коэффициент детерминации (r-квадрат): -0.10532093759756922
Среднее процентное отклонение (MAPE): 0.791843092261213
Абсолютная медианная ошибка: 1.0222130781087313
Максимальная ошибка: 11.166569277228058